### ISSUE TITLE
This example does not work with JupyterLab

### ISSUE THREAD

**Issue by fm75** [binder-examples/jupyter-extension#1]
If you [launch JupterLab](https://beta.mybinder.org/v2/gh/binder-examples/jupyter-extension/master?urlpath=lab) with this repo, the interactive part does not work.
Instead of showing the interactive widget and allowing interactions, the output cell shows:

<function __main__.plot_data(ii, cmap)>

I have been struggling to get something similar working with jupyterlab 1.0.4. After investigating this instance, I see that it is running jupyterlab 0.35.4.

Is there any way to get `binder` to work with jupyterlab extensions? Even an example with just a simple `ipywidget.IntSlider` might be helpful.

**Comment by marskar** [comment]
I asked a similar question on [Twitter](https://twitter.com/marskar/status/1172564018755788800). I think the `postBuild` commands are not being run for jupyterlab extensions, but I can install and enable extensions in the actual binder instance after it launches.
**UPDATE**: I fixed it. Here is a [working example with the jupyterlab-vim extension](https://mybinder.org/v2/gh/py4ds/PythonDataScienceHandbook/master?urlpath=lab/tree/notebooks/Index.ipynb)
Turns out filenames are case sensitive (`postBuild`👍`PostBuild`👎) 😅

**Comment by choldgraf** [comment]
Hey @fm75 - sorry for the slow response here, the binder-examples repositories don't get a ton of attention.

I think you're totally right that this repository should be made compatible with jupyter lab. You can definitely use lab extensions in Binder (for example, the [jupyterlab binder example repo](https://github.com/binder-examples/jupyterlab/blob/master/binder/postBuild) shows off the drawio extension).

The challenge w/ this repo is that the python-markdown extension hasn't been ported to jupyterlab, so we should probably remove it and choose an extension that works in both (maybe jupytext?)

@fm75 any interest in making a PR for this change? I'm happy to give it a review!

**Comment by fm75** [comment]
@choldgraf We could remove the markdown cell. My real issue is that it does not show the IntSlider nor the cmaps dropdown. I am wondering if this needs a fixed version of widgetsnbextension. I suspect that is the problem, because binder is using jupyterlab 0.35.4.
